---
title: "Police Violence and Racial Inequity in the United States"
date: "Autumn 2022"
output: 
  html_document:
    theme: journal
    toc: true
    toc_float: true
---
code name: PVRI

* Jinsu Jang (jjs9904@uw.edu)
* Bryce Penick (brypen@uw.edu)
* Justin Tang (jtan189@uw.edu)

INFO-201: Technical Foundations of Informatics - The Information School - University of Washington

## Abstract

Our main focus for this project is to identify any significant patterns regarding police violence, criminal activity, racial equity, and other factors influencing these activities in the United States. In analyzing these patterns, we will inspect multiple datasets that involves the characteristics of the many locations in which these violent events took place. With the rising political conversations regarding the police and the protection of the residents, we find it important to search for any correlations in these events for people to generate a more informed opinion surrounding the controversy.

Keywords

* Police activity
* Racial equity
* Crimes/Arrests/Casualties

## Introduction

For our project, we plan on visualizing and analyzing data in search of any prominent patterns in order to educate people on the controversial topic of police violence and its correlation of racial equity. The datasets that we are using involves a collection of casualties resulting from police response. This includes both the deaths of the victims and the police, along with demographic information such as age, race, gender, and the causes of death. Other data is presented in our study, such as the number of protests present from the outcome of these events, the amount of funding allocated for the police departments, the representation of the government parties, along with the quality of education and sources of housing present in each state. With all of this data, we hope to seek out any concerning patterns involving the mistreatment of violent activity and allow any citizens and activists to address these concerns with supported claims to fight for a more protected, united, responsible country.

## Problem Domain

Our project focuses on the links between police brutality and racial violence, along with the inequity at play there. This project aims to use objective data to try and see the links between the different issues and situations at play.

* Human Values

Datasets involving human lives often create a dilemma, as they can be seen as reducing the life of a human to a simple number. Our project strives to utilize this data to instead inform and try and find the correlations between the inequities in the United States and the police state. This data can be useful to try and break down these issues and begin to tackle them head on. The website listed below tracks human lives taken by police, police lives taken, and other important data that can be used to visualize better the human impacts at play. Police Violence Mapped

* Direct & Indirect Stakeholders

The direct stakeholders for our data would be the people utilizing them, whether that be activists, politicians or government officials. These people have the capacity to enact change through the data provided and directly make a change. Indirect stakeholders here would be families of victims, police or anyone else involved within the datasets. More will be covered about this in the next section, but this website highlights an activist group of people who had a family member killed by the police: United 4 Justice Group

* Harms & Benefit

If this data were to be utilized by direct stakeholders that are looking to create change and progress, it could lead to great results regarding limiting police brutality. However, data like this always has a cost, as it minimizes human suffering and deaths to statistics, but depending on the stakeholder this could be good or bad. Some unintended consequences could be, in areas with less police brutality, an argument could be made that there isn't a pandemic of police violence and racial inequity in the United States. This Stanford page offers multiple resources that shows the benefits that could be made utilizing similar data to what we're using. Stanford Cite

## Research Questions

1. What is the distribution of police and criminal activity within the United States?

Violence could possibly be presented unequally in the country, due to the uneven human population between each states, and the cities within those states. Other factors that can influence the violence rate can arise from the distribution of the population present, which can affect the overall societal climate. It is important to acknowledge the equality of the issue around the whole country, and dive deeper in figuring out what factors might influence the equality/inequality of the issue.

2. What does the demographic data tell us about the casualty patterns in each state?

One of the main addresses to the conversation of police activity is the assumption of bias in the outcome of each violent situation. Inspecting the demographic patterns of the victims, along with the demographic statistics of the whole state can help in identifying whether or not the issue of racial equity is present in each associated area, or if the cases are bordering the coincidental appearance. This allows us to search deeper into each case attentively.

3. How does conflict occur and how might it progress between interactions of the people and the police?

Conflict arrives in different methods and results in various outcomes depending on how aggressive he interactions are between the subjects. Being able to identify what types of arguments escalates into 
fatal encounters helps in understanding how each community differs in unison, which can reveal dividing trends in how our country operates. Identifying the different manners in which conflict in resolved is important to find the breaches of security to the communities around.

## The Dataset

Our dataset provides police-related violence and racial equity in the United States. The Law enforcement agencies and government provide insufficient numbers of lives killed by police during arrest, therefore the presence of documents about police killings that are supplied by the USA National Vital Statistics System (NVSS), FBI, and from other institutions are not well-organized. Due to this issue, figuring out the patterns between police violence and race through statistics from these resources is still difficult. Our dataset includes categorized data on police shootings, descriptive statistics for citizen fatalities involving police, and police officer deaths suffered in the line of duty. This can provide not only comprehensive accounting of people killed by police but also provides the relationship between police violence and racial equity. For example, Our data for citizens fatally shot by police provides names, dates, manner of death, whether the person was armed, age, race, city, state, signs of mental illness, threat level and the existence of body cam, and the location. Through the details of the citizens killed by the police, we can observe the patterns of people who killed by police. The pattern can be arrangd by age, race or locations. In regards to our dataset, since Jan. 1, 2015, the post of Fatal Force is regularly updated as fatal shootings are reported, and our dataset is updated as of Aug 2020.

By collecting this data, our dataset can report the details of citizens killed by the police. Moreover, through this dataset, we can observe police-related violence and racial equity more in-depth with the identification of police officers and citizens. Our data will benefitical for the public, organizations, and government by providing them an insight into the pattern of police violence and racial equity.

## Findings

There are a lot of unequal attention when it comes to the distribution of criminal and police violence
around the United States. When spectating the different areas of the nation, we found that the majority
of conflict arrives around the higher populated cities in the United States. These prime examples being Los Angeles, Chicago, and New York. When we searched for which demographic groups were targeted the most, we found there to be a common theme of White, Black, and Hispanic communities having a high influence in violence, where White communities were slightly higher in their proportions as compared to the Black and Hispanic communities combined. When inspecting the sources of these numbers nationwide, we found that the areas with a majorly high racial population proportion generally held the highest occurance of violence. Surprisingly, we found that these major cities with the most amount of conflict to share a division of hatred between the different minority groups present. More White states and cities presented a higher amount conflict with White communities being the primary subject. Gender seems to have played a major role in how violence is influenced, with males being targeted far more likely than females.

When looking at the trends between year gaps, there has been a general increase in violence overall. Although there has been a major divide between males and females, there has been a slight decline in the amount of males being targeted, with a slight increase in the amount of females being targeted. Violence between racial groups have remained stable, with White, Black, and Hispanic communities continuously topping the charts. Deaths occurring from these violent encounters retained a similar pattern, with an increase to Native Americans and Middle Eastern people. We also found these violent encounters to resolve with gun violence, which makes up the majority of deaths of the criminated and police forces in contact, and has continued to rise since the past decade.

## Discussion

## Conclusion

## Acknowledgments

We would like to use this short section as a quick shout out to John M., who created the data sets we are utilizing for our assignment. His data will help us create a clear and concise project that we hope turns out very well.

## References

Zero, C. (2022). Mapping police violence. Mapping Police Violence. Retrieved October 30, 2022, from https://mappingpoliceviolence.org/

(2015, May 7). Taking a stand against racial injustice and police brutality. FSI. Retrieved October 30, 2022, from https://fsi.stanford.edu/content/racial-injustice-and-police-brutality

Gilbert, G. (2019, September 5). Meet the families affected by police violence who are organizing to stop the killing. Waging Nonviolence. Retrieved October 30, 2022, from https://wagingnonviolence.org/2015/05/meet-families-affected-police-violence-organizing-stop-killing/